---
  - name: compose up
    docker_compose:
      project_src: "/opt/compose/{{ role_name }}"
      state: present

  - name: restart traefik
    docker_compose:
      project_src: /opt/compose/{{ role_name }}
      services: [ app ]
      restarted: yes

  - name: flush handlers
    meta: flush_handlers