- name: 'debian : add an apt signing key for docker'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: 'debian : add apt repository for stable version'
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: 'debian : install docker and its dependencies'
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
    update_cache: yes

- name: ensure docker directory
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: copy docker daemon config
  copy:
    src: daemon.json
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: 0644
  notify: restart docker

- name: ensure systemd docker.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: systemd docker drop-in
  copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: 0755
    src: override.conf
  notify: restart docker

- name: flush handlers
  meta: flush_handlers